print("Course - DevOps")
print("Credit - 3")
print("Course - SPM")
print("Credit - 3")
print("Course - Career Skills")
print("Credit - 3")
print("Course - HPC")
print("Credit - 4")
print("Course - MS")
print("Credit - 3")
